name: Sync Submodules

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  sync-wikis:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Sync wikis
        run: |
          git submodule foreach '
            echo "Updating submodule: $name"
            if git fetch origin && git reset --hard origin/master || git reset --hard origin/main; then
              echo "Successfully updated $name"
            else
              echo "Failed to update $name" >&2
              exit 1
            fi
          '
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff-index --quiet HEAD; then
            echo "No hay cambios que subir."
          else
            git add .
            git commit -m "Sync wikis to latest commits"
            git push
          fi